services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mercado
      MYSQL_USER: enzo
      MYSQL_PASSWORD: Familianunes123.
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  app:
    build: .
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/mercado
      SPRING_DATASOURCE_USERNAME: enzo
      SPRING_DATASOURCE_PASSWORD: Familianunes123.